### ISSUE TITLE
peerDependencies includes eslint-config-airbnb@^15, much older than the current 19.0.4

### ISSUE THREAD

**Issue by marvold-mw** [Kenneth-Sills/eslint-config-airbnb-typescript#19]
First, thanks for taking on maintenance of a fork of this project!

While testing this fork out, I ran into issues; we have upstream eslint-config-airbnb 19.0.4 installed for frontend projects.  However, this version specifies a peer dependency on major version 15, which leads to conflicts.  While 15 is the latest version for eslint-config-airbnb-base, the two airbnb configs have different major version numbers and version 15 of the full frontend config dates back to 2017.  I suspect this is an oversight, but it would be good if this project was using the latest version of the upstream package.

**Comment by Kenneth-Sills** [comment]
Thank you, I appreciate the report! What an embarrassing oversight on my part. :sweat_smile: 

I've published [v20](https://github.com/Kenneth-Sills/eslint-config-airbnb-typescript/releases/tag/v20.0.0), which should now have the correct peer dependency requirement for `eslint-config-aribnb`. Please do let me know if you have any other issues!

**Comment by marvold-mw** [comment]
No worries, thanks for the quick response!
